[package]
name = "mqtt-reeze"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
rumqttc = "0.22"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["rt", "time"] }
